"""Send email alerts for new jobs via SMTP."""
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

log = logging.getLogger(__name__)


def _build_html(jobs: list[dict]) -> str:
    rows = ""
    for j in jobs:
        rows += (
            f"<tr>"
            f"<td><a href='{j['url']}'>{j['title']}</a></td>"
            f"<td>{j['company']}</td>"
            f"<td>{j['location']}</td>"
            f"<td>{j['posted_at']}</td>"
            f"<td>{j['source']}</td>"
            f"</tr>\n"
        )
    return f"""
    <html><body>
    <h2>🔍 Job Scout: {len(jobs)} New Business Analyst Job(s)</h2>
    <table border="1" cellpadding="6" cellspacing="0">
    <tr>
        <th>Title</th><th>Company</th><th>Location</th>
        <th>Posted At</th><th>Source</th>
    </tr>
    {rows}
    </table>
    <p style="color:gray;font-size:12px;">Generated by job_scout</p>
    </body></html>
    """


def _build_text(jobs: list[dict]) -> str:
    lines = [f"Job Scout: {len(jobs)} New Business Analyst Job(s)\n"]
    for j in jobs:
        lines.append(
            f"  [{j['source'].upper()}] {j['title']} @ {j['company']}\n"
            f"  Location: {j['location']}\n"
            f"  Posted:   {j['posted_at']}\n"
            f"  URL:      {j['url']}\n"
        )
    return "\n".join(lines)


def send_alerts(new_jobs: list[dict]) -> None:
    """Send email for new jobs. Silently skips if env vars are missing."""
    if not new_jobs:
        return

    smtp_host = os.environ.get("SMTP_HOST")
    smtp_port = os.environ.get("SMTP_PORT", "587")
    smtp_user = os.environ.get("SMTP_USER")
    smtp_pass = os.environ.get("SMTP_PASS")
    smtp_tls = os.environ.get("SMTP_TLS", "true").lower() != "false"
    email_from = os.environ.get("EMAIL_FROM", smtp_user)
    email_to_raw = os.environ.get("EMAIL_TO", "")

    if not all([smtp_host, smtp_user, smtp_pass, email_to_raw]):
        log.info("Email alerts skipped: SMTP env vars not fully configured.")
        return

    recipients = [e.strip() for e in email_to_raw.split(",") if e.strip()]
    if not recipients:
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[Job Scout] {len(new_jobs)} New BA Job(s) Found"
    msg["From"] = email_from
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(_build_text(new_jobs), "plain"))
    msg.attach(MIMEText(_build_html(new_jobs), "html"))

    try:
        port = int(smtp_port)
        if smtp_tls:
            with smtplib.SMTP(smtp_host, port, timeout=30) as server:
                server.ehlo()
                server.starttls()
                server.login(smtp_user, smtp_pass)
                server.sendmail(email_from, recipients, msg.as_string())
        else:
            with smtplib.SMTP_SSL(smtp_host, port, timeout=30) as server:
                server.login(smtp_user, smtp_pass)
                server.sendmail(email_from, recipients, msg.as_string())
        log.info("Email alert sent to %s", recipients)
    except Exception as exc:
        log.warning("Failed to send email alert: %s", exc)
